#version: "1"

services:
  bpmtomcat:
    build: ./docker-camunda-bpm-platform
    #ports:
      #- "8080:8080"
    depends_on:
      - bpmdb
    environment:
      - WAIT_FOR=bpmdb:5432
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://bpmdb:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
  bpmdb:
    build: ./postgres-camunda-bpm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
